### ISSUE TITLE
Settle duplicate courses in different areas

### ISSUE THREAD

**Issue by churichard** [TigerPathApp/tigerpath#41]
It should be possible to have duplicates of the same course in the schedule and settle the duplicates in different areas of the req tree

**Comment by bnehoran** [comment]
#### Funny note
There's a workaround: If you try to settle a duplicated class in two different requirements, settling it in the second requirement pops up an extraneous version of it as unsettled. Clicking on it to settle it, and then to unsettle it, causes it to disappear, leaving behind the desired result.

**Comment by danielleung27** [comment]
Fixed in #50
