### ISSUE TITLE
Bug: Courses disappearing from requirements tree

### ISSUE THREAD

**Issue by bnehoran** [TigerPathApp/tigerpath#44]
Courses disappear whenever they are settled in requirements whose names contain commas.

One such example is
`"Woodrow Wilson School of Public and International Affairs//Prerequisites//Politics, Sociology or Psychology Prerequisite"`
Try settling `SOC222` in it, for example.

Or try settling `AST309 / ENE309 / MAE309 / PHY309` in 
`"Woodrow Wilson School of Public and International Affairs//Core//Elective Courses//Security and Sustainability//Environment, Climate, and Energy"`

I believe this is because the settled list is stored as a comma separated string.
Either find a way to store an actual list, or escape the identifiers of requirements before adding them (and unescape when reading).

**Comment by danielleung27** [comment]
Bug fixed
